#!/bin/csh -f

rm -f .depends

# generate dependencies:

set xx = FAQ-pp2html-slides/slide0000.htm
foreach f (`find faq-pp2html -name \*.pp`)
  echo "${xx}: $f" >> .depends
end

set xx = FAQ-parser-slides/slide0000.htm
foreach f (`find faq -name \*.pp`)
  echo "${xx}: $f" >> .depends
end

set xx = REF-pp2html-slides/slide0000.htm
foreach f (`find tags -name \*.pp`)
  echo "${xx}: $f" >> .depends
end
